apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metric2deploy
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/kernel-paniccc/Metric2Deploy.git
